@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="about">
            <div class="par">
            <p>
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Labore aperiam impedit repudiandae veniam eaque molestias sunt excepturi numquam magni tenetur amet saepe in libero dolorum vero dolore autem reprehenderit minus totam ad aut, ipsam consectetur maiores laborum. Velit, esse pariatur aliquam dolorum sed, error similique omnis tempore soluta quasi magni adipisci voluptates quod, molestias mollitia itaque? Ratione libero ipsam quos voluptates molestiae sint earum consectetur excepturi provident possimus nulla corrupti quam neque architecto omnis, labore tempora sapiente impedit quibusdam aperiam exercitationem asperiores. Consequatur repellendus facere, at consequuntur reiciendis amet pariatur doloremque earum quisquam beatae provident architecto impedit magni dolorem nesciunt sit sed ullam dolorum doloribus ratione animi modi, minus vero assumenda. Facere sit similique, quidem fuga nam accusantium necessitatibus saepe culpa consequuntur! Molestiae vel cumque veniam ea amet voluptatibus dolorum perferendis fuga, provident error ex dolore dolor, nam blanditiis animi repellat quae nemo magni laborum nesciunt officiis distinctio! Quasi soluta dolor repellat, quis voluptatum esse, aliquid debitis tenetur non omnis molestias fuga odit vel molestiae totam sapiente vero numquam voluptates magni facilis error ab, eos repellendus modi? Nisi aliquid ipsa illum totam eum doloremque facere modi id at animi? Earum libero similique, dignissimos molestias, officiis eius atque perferendis delectus officia ab molestiae sequi odio harum nobis impedit omnis quos numquam optio soluta vero. Magni laudantium velit saepe animi dicta aut tempore quod, sunt vel unde sed vero expedita tempora repudiandae totam reprehenderit voluptates ratione facilis accusantium doloremque. Eveniet molestias non nostrum dolorum molestiae quo quam reiciendis dicta illum nobis doloremque enim a ex obcaecati incidunt, adipisci itaque voluptate at quibusdam perspiciatis ullam iure doloribus eaque? Fuga harum, modi necessitatibus totam illo assumenda fugit nostrum unde perspiciatis amet sunt, iste, mollitia ea voluptate qui? Minus nam recusandae dolorum eaque quibusdam numquam ipsam rem aliquid pariatur quod, voluptatum beatae consectetur saepe tempore.
            </p>
            </div>
            <div class="par">
            <p>
                    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Labore aperiam impedit repudiandae veniam eaque molestias sunt excepturi numquam magni tenetur amet saepe in libero dolorum vero dolore autem reprehenderit minus totam ad aut, ipsam consectetur maiores laborum. Velit, esse pariatur aliquam dolorum sed, error similique omnis tempore soluta quasi magni adipisci voluptates quod, molestias mollitia itaque? Ratione libero ipsam quos voluptates molestiae sint earum consectetur excepturi provident possimus nulla corrupti quam neque architecto omnis, labore tempora sapiente impedit quibusdam aperiam exercitationem asperiores. Consequatur repellendus facere, at consequuntur reiciendis amet pariatur doloremque earum quisquam beatae provident architecto impedit magni dolorem nesciunt sit sed ullam dolorum doloribus ratione animi modi, minus vero assumenda. Facere sit similique, quidem fuga nam accusantium necessitatibus saepe culpa consequuntur! Molestiae vel cumque veniam ea amet voluptatibus dolorum perferendis fuga, provident error ex dolore dolor, nam blanditiis animi repellat quae nemo magni laborum nesciunt officiis distinctio! Quasi soluta dolor repellat, quis voluptatum esse, aliquid debitis tenetur non omnis molestias fuga odit vel molestiae totam sapiente vero numquam voluptates magni facilis error ab, eos repellendus modi? Nisi aliquid ipsa illum totam eum doloremque facere modi id at animi? Earum libero similique, dignissimos molestias, officiis eius atque perferendis delectus officia ab molestiae sequi odio harum nobis impedit omnis quos numquam optio soluta vero. Magni laudantium velit saepe animi dicta aut tempore quod, sunt vel unde sed vero expedita tempora repudiandae totam reprehenderit voluptates ratione facilis accusantium doloremque. Eveniet molestias non nostrum dolorum molestiae quo quam reiciendis dicta illum nobis doloremque enim a ex obcaecati incidunt, adipisci itaque voluptate at quibusdam perspiciatis ullam iure doloribus eaque? Fuga harum, modi necessitatibus totam illo assumenda fugit nostrum unde perspiciatis amet sunt, iste, mollitia ea voluptate qui? Minus nam recusandae dolorum eaque quibusdam numquam ipsam rem aliquid pariatur quod, voluptatum beatae consectetur saepe tempore.
            </p>
            </div>
        </div>
    </div>

@endsection